#!/usr/bin/env node
// Generates src/buildinfo.ts with version + git metadata so the compiled
// CLI can print which build is running. Safe when .git is missing.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');

function git(args) {
  const r = spawnSync('git', args, { cwd: root, encoding: 'utf8' });
  if (r.status !== 0) return '';
  return (r.stdout || '').trim();
}

const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));
const hasGit = existsSync(resolve(root, '.git'));

const commit     = hasGit ? git(['rev-parse', '--short=8', 'HEAD']) : '';
const commitDate = hasGit ? git(['log', '-1', '--format=%cI']) : '';
const branch     = hasGit ? git(['rev-parse', '--abbrev-ref', 'HEAD']) : '';
const dirty      = hasGit ? (git(['status', '--porcelain']) ? '-dirty' : '') : '';
const buildDate  = new Date().toISOString();

const out = `// AUTO-GENERATED by scripts/buildinfo.mjs — do not edit.
export const BUILD_INFO = {
  version: ${JSON.stringify(pkg.version)},
  commit: ${JSON.stringify(commit + dirty)},
  commitDate: ${JSON.stringify(commitDate)},
  branch: ${JSON.stringify(branch)},
  buildDate: ${JSON.stringify(buildDate)},
} as const;

export function formatBuildInfo(): string {
  const { version, commit, commitDate } = BUILD_INFO;
  const parts = [\`v\${version}\`];
  if (commit) parts.push(commit);
  if (commitDate) parts.push(commitDate);
  return parts.join(' · ');
}
`;
writeFileSync(resolve(root, 'src/buildinfo.ts'), out);
console.log('[buildinfo]', JSON.stringify({ version: pkg.version, commit, commitDate, branch, dirty }));
